version: 2
updates:
  # Maintain dependencies for Go modules
  - package-ecosystem: "gomod"
    directory: "/" # `go.mod` is at the root
    schedule:
      interval: "weekly"
    labels:
      - "go"
      - "dependencies"
    # Group non-major Go module updates together to reduce noise
    groups:
      gomod-patch-and-minor:
        update-types:
          - "minor"
          - "patch"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/" # Look for workflows in `.github/workflows`
    schedule:
      interval: "weekly"
    labels:
      - "ci"
      - "dependencies"
