package main

import (
	"bufio"
	"bytes"
	"crypto/ed25519"
	"crypto/rand"
	"encoding/pem"
	"fmt"
	"log"
	"os"
	"strings"
	"sync"

	"github.com/spf13/cobra"
	"github.com/spf13/viper"
	"github.com/toeirei/keymaster/internal/crypto/ssh"
	"github.com/toeirei/keymaster/internal/db"
	"github.com/toeirei/keymaster/internal/deploy"
	"github.com/toeirei/keymaster/internal/model"
	"github.com/toeirei/keymaster/internal/sshkey"
	"github.com/toeirei/keymaster/internal/tui"
)

var version = "dev" // this will be set by the linker
var cfgFile string

func main() {
	if err := rootCmd.Execute(); err != nil {
		// The error is already printed by Cobra on failure.
		os.Exit(1)
	}
}

var rootCmd = &cobra.Command{
	Use:   "keymaster",
	Short: "Keymaster is a lightweight, agentless SSH access manager.",
	Long: `Keymaster centralizes control of authorized_keys files.
Instead of scattering user keys everywhere, Keymaster plants a single
system key per account and uses it as a foothold to rewrite and
version-control access. A database becomes the source of truth.

Running without a subcommand will launch the interactive TUI.`,
	PersistentPreRunE: func(cmd *cobra.Command, args []string) error {
		// Initialize the database for all commands.
		// Viper has already read the config by this point.
		dbType := viper.GetString("database.type")
		dsn := viper.GetString("database.dsn")
		if err := db.InitDB(dbType, dsn); err != nil {
			return fmt.Errorf("error initializing database: %w", err)
		}
		return nil
	},
	Run: func(cmd *cobra.Command, args []string) {
		// The database is already initialized by PersistentPreRunE.
		tui.Run()
	},
}

func init() {
	cobra.OnInitialize(initConfig)

	rootCmd.Version = version
	rootCmd.PersistentFlags().StringVar(&cfgFile, "config", "", "config file (default is $HOME/.keymaster.yaml or ./keymaster.yaml)")

	// Database flags
	rootCmd.PersistentFlags().String("db-type", "sqlite", "Database type (e.g., sqlite, postgres)")
	rootCmd.PersistentFlags().String("db-dsn", "./keymaster.db", "Database connection string (DSN)")

	// Bind flags to viper
	viper.BindPFlag("database.type", rootCmd.PersistentFlags().Lookup("db-type"))
	viper.BindPFlag("database.dsn", rootCmd.PersistentFlags().Lookup("db-dsn"))

	// Set defaults in viper. These are used if not set in the config file or by flags.
	viper.SetDefault("database.type", "sqlite")
	viper.SetDefault("database.dsn", "./keymaster.db")

	// Add commands
	rootCmd.AddCommand(deployCmd)
	rootCmd.AddCommand(rotateKeyCmd)
	rootCmd.AddCommand(auditCmd)
	rootCmd.AddCommand(importCmd)
	rootCmd.AddCommand(trustHostCmd)
}

// initConfig reads in config file and ENV variables if set.
func initConfig() {
	if cfgFile != "" {
		// Use config file from the flag.
		viper.SetConfigFile(cfgFile)
	} else {
		// Find home directory.
		home, err := os.UserHomeDir()
		cobra.CheckErr(err)

		// Search config in home directory and current directory with name ".keymaster" (without extension).
		viper.AddConfigPath(home)
		viper.AddConfigPath(".")
		viper.SetConfigType("yaml")
		viper.SetConfigName(".keymaster")
	}

	viper.SetEnvPrefix("KEYMASTER")
	viper.AutomaticEnv() // read in environment variables that match

	// If a config file is found, read it in.
	if err := viper.ReadInConfig(); err != nil {
		// If the config file is not found, we can create one with default values
		// to make configuration discoverable for the user.
		if _, ok := err.(viper.ConfigFileNotFoundError); ok && cfgFile == "" {
			// We only do this if no config file was found and none was specified via flag.
			// We'll attempt to write a default config to the current directory.
			const defaultConfigPath = ".keymaster.yaml"
			defaultContent := `# Keymaster configuration file.
# This file is automatically generated with default values.
# You can modify these settings to configure Keymaster.

database:
  # The type of database to use. Supported values: "sqlite".
  # "postgres" is planned for future versions.
  type: sqlite

  # The Data Source Name (DSN) for the database connection.
  # For SQLite, this is the path to the database file.
  dsn: ./keymaster.db

# Example for future PostgreSQL configuration:
# database:
#   type: postgres
#   dsn: "host=localhost user=keymaster password=secret dbname=keymaster port=5432 sslmode=disable"
`
			// If writing fails (e.g., due to permissions), we don't treat it as a
			// fatal error. The app will simply run with the default values set in memory.
			_ = os.WriteFile(defaultConfigPath, []byte(defaultContent), 0644)
		}
	}
}

var deployCmd = &cobra.Command{
	Use:   "deploy [user@host]",
	Short: "Deploy authorized_keys to one or all hosts",
	Long: `Renders the authorized_keys file from the database state and deploys it.
If an account (user@host) is specified, deploys only to that account.
If no account is specified, deploys to all active accounts in the database.`,
	Args: cobra.MaximumNArgs(1),
	Run: func(cmd *cobra.Command, args []string) {
		// DB is initialized in PersistentPreRunE.
		allAccounts, err := db.GetAllActiveAccounts()
		if err != nil {
			log.Fatalf("Error getting accounts: %v", err)
		}

		var targetAccounts []model.Account
		if len(args) > 0 {
			target := args[0]
			found := false
			for _, acc := range allAccounts {
				if acc.String() == target {
					targetAccounts = append(targetAccounts, acc)
					found = true
					break
				}
			}
			if !found {
				log.Fatalf("Account '%s' not found or is not active.", target)
			}
		} else {
			targetAccounts = allAccounts
		}

		if len(targetAccounts) == 0 {
			fmt.Println("No active accounts to deploy to.")
			return
		}

		var wg sync.WaitGroup
		results := make(chan string, len(targetAccounts))

		fmt.Printf("🚀 Starting deployment to %d account(s)...\n", len(targetAccounts))

		for _, acc := range targetAccounts {
			wg.Add(1)
			go func(account model.Account) {
				defer wg.Done()
				err := runDeploymentForAccount(account)
				details := fmt.Sprintf("account: %s", account.String())
				if err != nil {
					results <- fmt.Sprintf("💥 Failed to deploy to %s: %v", account.String(), err)
					_ = db.LogAction("DEPLOY_FAIL", fmt.Sprintf("%s, error: %v", details, err))
				} else {
					results <- fmt.Sprintf("✅ Successfully deployed to %s", account.String())
					_ = db.LogAction("DEPLOY_SUCCESS", details)
				}
			}(acc)
		}

		go func() {
			wg.Wait()
			close(results)
		}()

		for res := range results {
			fmt.Println(res)
		}
		fmt.Println("\nDeployment complete.")
	},
}

var rotateKeyCmd = &cobra.Command{
	Use:   "rotate-key",
	Short: "Rotates the active Keymaster system key",
	Long: `Generates a new ed25519 key pair, saves it to the database, and sets it as the active key.
The previous key is kept for accessing hosts that have not yet been updated.`,
	Run: func(cmd *cobra.Command, args []string) {
		fmt.Println("⚙️  Rotating system key...")
		// DB is initialized in PersistentPreRunE.
		pubKey, privKey, err := ed25519.GenerateKey(rand.Reader)
		if err != nil {
			log.Fatalf("Error generating key pair: %v", err)
		}

		sshPubKey, err := ssh.NewPublicKey(pubKey)
		if err != nil {
			log.Fatalf("Error creating SSH public key: %v", err)
		}
		pubKeyBytes := ssh.MarshalAuthorizedKey(sshPubKey)
		publicKeyString := fmt.Sprintf("%s keymaster-system-key", strings.TrimSpace(string(pubKeyBytes)))

		pemBlock, err := ssh.MarshalEd25519PrivateKey(privKey, "")
		if err != nil {
			log.Fatalf("Error marshaling private key: %v", err)
		}
		privateKeyString := string(pem.EncodeToMemory(pemBlock))

		serial, err := db.RotateSystemKey(publicKeyString, privateKeyString)
		if err != nil {
			log.Fatalf("Error saving rotated key to database: %v", err)
		}

		fmt.Printf("\n✅ Successfully rotated system key. The new active key is serial #%d.\n", serial)
		fmt.Println("Run 'keymaster deploy' to apply the new key to your fleet.")
	},
}

var auditCmd = &cobra.Command{
	Use:   "audit",
	Short: "Audit hosts for configuration drift",
	Long:  `Connects to all active hosts and checks if their deployed authorized_keys file has the expected Keymaster serial number.`,
	Run: func(cmd *cobra.Command, args []string) {
		// DB is initialized in PersistentPreRunE.
		accounts, err := db.GetAllActiveAccounts()
		if err != nil {
			log.Fatalf("Error getting accounts: %v", err)
		}

		if len(accounts) == 0 {
			fmt.Println("No active accounts to audit.")
			return
		}

		var wg sync.WaitGroup
		results := make(chan string, len(accounts))

		fmt.Printf("🔬 Starting audit of %d account(s)...\n", len(accounts))

		for _, acc := range accounts {
			wg.Add(1)
			go func(account model.Account) {
				defer wg.Done()
				err := runAuditForAccount(account)
				details := fmt.Sprintf("account: %s", account.String())
				if err != nil {
					results <- fmt.Sprintf("🚨 Drift detected on %s: %v", account.String(), err)
					_ = db.LogAction("AUDIT_FAIL", fmt.Sprintf("%s, error: %v", details, err))
				} else {
					results <- fmt.Sprintf("✅ OK: %s", account.String())
					_ = db.LogAction("AUDIT_SUCCESS", details)
				}
			}(acc)
		}

		go func() {
			wg.Wait()
			close(results)
		}()

		for res := range results {
			fmt.Println(res)
		}
		fmt.Println("\nAudit complete.")
	},
}

var importCmd = &cobra.Command{
	Use:   "import [authorized_keys_file]",
	Short: "Import public keys from an authorized_keys file",
	Long:  `Reads a standard authorized_keys file and imports the public keys into the Keymaster database.`,
	Args:  cobra.ExactArgs(1), // Ensures we get exactly one file path
	Run: func(cmd *cobra.Command, args []string) {
		filePath := args[0]
		// DB is initialized in PersistentPreRunE.
		fmt.Printf("🔑 Importing keys from %s...\n", filePath)

		file, err := os.Open(filePath)
		if err != nil {
			fmt.Printf("Error opening file: %v\n", err)
			os.Exit(1)
		}
		defer file.Close()

		scanner := bufio.NewScanner(file)
		importedCount := 0
		skippedCount := 0

		for scanner.Scan() {
			line := strings.TrimSpace(scanner.Text())

			// Skip empty lines or comments
			if line == "" || strings.HasPrefix(line, "#") {
				continue
			}

			alg, keyData, comment, err := sshkey.Parse(line)
			if err != nil {
				skippedCount++
				continue
			}

			if comment == "" {
				fmt.Printf("  - Skipping key with empty comment: %.20s...\n", keyData)
				skippedCount++
				continue
			}

			if err := db.AddPublicKey(alg, keyData, comment); err != nil {
				if strings.Contains(err.Error(), "UNIQUE constraint failed") {
					fmt.Printf("  - Skipping duplicate key (comment exists): %s\n", comment)
				} else {
					fmt.Printf("  - Error adding key '%s': %v\n", comment, err)
				}
				skippedCount++
				continue
			}

			fmt.Printf("  + Imported key: %s\n", comment)
			importedCount++
		}

		fmt.Printf("\n✅ Import complete. Imported %d keys, skipped %d.\n", importedCount, skippedCount)
	},
}

func runDeploymentForAccount(account model.Account) error {
	var connectKey *model.SystemKey
	var err error
	if account.Serial == 0 {
		connectKey, err = db.GetActiveSystemKey()
		if err != nil {
			return fmt.Errorf("failed to get active system key for bootstrap: %w", err)
		}
		if connectKey == nil {
			return fmt.Errorf("no active system key found for bootstrap")
		}
	} else {
		connectKey, err = db.GetSystemKeyBySerial(account.Serial)
		if err != nil {
			return fmt.Errorf("failed to get system key with serial %d: %w", account.Serial, err)
		}
		if connectKey == nil {
			return fmt.Errorf("db inconsistency: no system key found for serial %d", account.Serial)
		}
	}

	content, err := deploy.GenerateKeysContent(account.ID)
	if err != nil {
		return err
	}
	activeKey, err := db.GetActiveSystemKey()
	if err != nil || activeKey == nil {
		return fmt.Errorf("could not retrieve active system key for serial update")
	}

	deployer, err := deploy.NewDeployer(account.Hostname, account.Username, connectKey.PrivateKey)
	if err != nil {
		return fmt.Errorf("connection failed: %w", err)
	}
	defer deployer.Close()

	if err := deployer.DeployAuthorizedKeys(content); err != nil {
		return fmt.Errorf("deployment failed: %w", err)
	}

	if err := db.UpdateAccountSerial(account.ID, activeKey.Serial); err != nil {
		return fmt.Errorf("db update failed after successful deploy: %w", err)
	}

	return nil
}

var trustHostCmd = &cobra.Command{
	Use:   "trust-host <user@host>",
	Short: "Adds a host's public key to the list of known hosts",
	Long: `Connects to a host for the first time, retrieves its public key,
and prompts the user to save it to the database. This is a required
step before Keymaster can manage a new host.`,
	Args: cobra.ExactArgs(1),
	Run: func(cmd *cobra.Command, args []string) {
		// DB is initialized in PersistentPreRunE.
		target := args[0]
		parts := strings.Split(target, "@")
		if len(parts) != 2 {
			log.Fatalf("Invalid account format. Expected user@host.")
		}
		hostname := parts[1]

		fmt.Printf("Attempting to retrieve host key from %s...\n", hostname)
		key, err := deploy.GetRemoteHostKey(hostname)
		if err != nil {
			log.Fatalf("Could not get host key: %v", err)
		}

		fingerprint := ssh.FingerprintSHA256(key)
		fmt.Printf("\nThe authenticity of host '%s' can't be established.\n", hostname)
		fmt.Printf("%s key fingerprint is %s.\n", key.Type(), fingerprint)

		if warning := sshkey.CheckHostKeyAlgorithm(key); warning != "" {
			fmt.Printf("\n%s\n", warning)
		}

		fmt.Print("Are you sure you want to continue connecting (yes/no)? ")

		reader := bufio.NewReader(os.Stdin)
		answer, _ := reader.ReadString('\n')
		answer = strings.TrimSpace(strings.ToLower(answer))

		if answer != "yes" {
			fmt.Println("Host key not trusted. Aborting.")
			os.Exit(1)
		}

		keyStr := string(ssh.MarshalAuthorizedKey(key))
		if err := db.AddKnownHostKey(hostname, keyStr); err != nil {
			log.Fatalf("Failed to save host key to database: %v", err)
		}

		fmt.Printf("Warning: Permanently added '%s' (type %s) to the list of known hosts.\n", hostname, key.Type())
	},
}

func runAuditForAccount(account model.Account) error {
	connectKey, err := db.GetSystemKeyBySerial(account.Serial)
	if err != nil {
		return fmt.Errorf("could not get system key %d from db: %w", account.Serial, err)
	}
	if connectKey == nil {
		// If serial is 0, it's a new host, which is technically not out of sync.
		if account.Serial == 0 {
			return fmt.Errorf("host has not been deployed to yet (serial is 0)")
		}
		return fmt.Errorf("db inconsistency: no system key found for serial %d", account.Serial)
	}

	deployer, err := deploy.NewDeployer(account.Hostname, account.Username, connectKey.PrivateKey)
	if err != nil {
		return fmt.Errorf("connection failed: %w", err)
	}
	defer deployer.Close()

	remoteContent, err := deployer.GetAuthorizedKeys()
	if err != nil {
		return fmt.Errorf("could not read remote authorized_keys: %w", err)
	}

	// Scan the entire file for the Keymaster serial comment, which is more robust
	// than just checking the first line.
	var remoteSerial = -1 // Use a value that can't be a valid serial
	scanner := bufio.NewScanner(bytes.NewReader(remoteContent))
	for scanner.Scan() {
		line := scanner.Text()
		serial, err := sshkey.ParseSerial(line)
		if err == nil {
			// Found it!
			remoteSerial = serial
			break
		}
	}

	if remoteSerial == -1 {
		return fmt.Errorf("Keymaster serial comment not found in remote file")
	}

	if remoteSerial != account.Serial {
		return fmt.Errorf("remote serial (%d) does not match database serial (%d)", remoteSerial, account.Serial)
	}

	return nil
}
