# .github/workflows/release.yml
name: Release

on:
  push:
    # This workflow will run only when you push a tag that starts with 'v'
    # For example: v1.2.1, v1.3.0, etc.
    tags:
      - 'v*.*.*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history so GoReleaser can generate a changelog if needed

      - name: Set up Go
        uses: actions/setup-go@v5

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          # 'latest' will use the latest GoReleaser version
          version: latest
          # The '--clean' flag removes the 'dist' directory before building
          args: release --clean
        env:
          # This token is provided by GitHub automatically and is required
          # to create a release and upload assets.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}